package org.hongxing.site.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserOsc<M extends BaseUserOsc<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setUserid(Integer userid) {
		set("userid", userid);
	}

	public Integer getUserid() {
		return get("userid");
	}

	public void setOscid(String oscid) {
		set("oscid", oscid);
	}

	public String getOscid() {
		return get("oscid");
	}

	public void setOscnick(String oscnick) {
		set("oscnick", oscnick);
	}

	public String getOscnick() {
		return get("oscnick");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
