package org.hongxing.site.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDonate<M extends BaseDonate<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setAmount(Double amount) {
		set("amount", amount);
	}

	public Double getAmount() {
		return get("amount");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setUrl(String url) {
		set("url", url);
	}

	public String getUrl() {
		return get("url");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setWay(String way) {
		set("way", way);
	}

	public String getWay() {
		return get("way");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return get("remark");
	}

	public void setLeavemsg(String leavemsg) {
		set("leavemsg", leavemsg);
	}

	public String getLeavemsg() {
		return get("leavemsg");
	}

	public void setMyremark(String myremark) {
		set("myremark", myremark);
	}

	public String getMyremark() {
		return get("myremark");
	}

}
