package org.tio.site.model;

import org.tio.site.model.base.BaseUserOsc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserOsc extends BaseUserOsc<UserOsc> {
	
}
